#!/bin/bash

#Küsib kellaaega
echo -n "Sisesta kellaaeg täistunnina: "
read kell

#Kontrollib, et kas on hommik
if test $kell -ge 6 -a $kell -lt 12
then
	echo "Tere hommikust"

#Kontrollib, et kas tegu on päevase ajaga
elif test $kell -ge 12 -a $kell -lt 18
then
	echo "Tere päevast"

#Kontrollib kas on õhtu
elif test $kell -ge 18 -a $kell -lt 22
then
	echo "Tere õhtust"

%Kontrollib kas tegu on ööga
elif test $kell -ge 22 -a $kell -le 24 -o $kell -ge 0 -a $kell -lt 6
then
	echo "Head ööd"

#Kui on sisestatud vale aeg
else
	echo "Arv ei ole 0 ja 24 vahel"
fi

