#!/bin/bash
#Sisestatakse suvaline arv, nende numbrid liidetakse kokku

echo -n "Sisesta suvaline täisarv: "
read arv
#Summale väärtus
summa=0
#Lisan s (sisestatud arv) teise teisenduse
#Ring käib nii kaua kuni s on 0
while [ $arv -ne 0 ]
do
#Jäägi leidmine ja seejärel 19ga jagamine
	jaak=$((arv % 10))
#Lisatakse summasse
	summa=$(($summa + $jaak))
#Väljastab ülejäänud arvud
	arv=$(($arv / 10))
done
echo "Arvu summa on $summa"
