#!/bin/bash

echo -n "Sisesta oma ees- ja perenimi: " #Prindib välja rea, et kirjeldada, mida pead järgmisena kirjutama 
read eesnimi perenimi #Sisestad eelmises  reas öeldud info, eesnimi on 1. sõna ja perenimi on 2. sõna, perenimi võib olla lõpmata pikk, eesnimi ainult 1 sõna
echo "Sinu eesnimi on $eesnimi ja perenimi on $perenimi" #Prindib tulemuse
