#!/bin/bash

#Esitan küsimusi, et leida vajalikud arvud
echo -n "Sisesta aluskandiku pikkus ja laius cm-tes " #Tekst kirjeldab, et mida  pead vastama ja mitu arvu on vaja
read pikkus laius #Sisestad arvud ja määrad nendele shortcutid
echo -n "Kui suuri küpsiseid tahad tordile? (cm-tes; pikkus ja laius) " #Kajab, et kui suurt küpsist tahad
read pikkus1 laius2 #Leiab informatsiooni küpsiste suuruseks
echo -n "Mitu kihti soovid tordile? " #Küsib et mitu kihti on vaja
read kihti #Määrab vastatud arvule shortcutiks kihti
echo -n "Mitu küpsist on pakis? " #Küsib mitu küpsist on pakis
read pakis #Määrab vastusele shortcuti pakis

#arvutan pakkide arvu
#Lihtsustan tehteid
kandik=`expr $pikkus \* $laius`
kypspind=`expr $pikkus1 \* $laius2`
yheskihis=`expr $kandik / $kypspind`
jaakkihis=`expr $kandik % $kypspind`
jaakkokku=`expr $jaakkihis \* $kihti`
kypsisveel=`expr $jaakkokku / $kypspind`
kypsised1=`expr $yheskihis \* $kihti`
kypsisedkokku=`expr $kypsised1 + $kypsisveel`
pakkarv=`expr $kypsisedkokku / $pakis`
jaak=`expr $kypsisedkokku % $pakis`
echo "Kokku on vaja $pakkarv pakki ja lisaks veel $jaak küpsist"
echo "Kui siin ei ole NULL: $jaakkokku siis veel 1 küpsis"
