#!/bin/bash

#Küsib andmeid
echo -n "Mitu rida soovid? "
read rida
echo -n "Mitu tulpa soovid? "
read tulpa

#Tsükkel ridade vahetuseks ja arvu suurendamise kohta
for (( i=1; i<=$rida; i++ ))
do
#Tsükkel väljastamaks ridadesse ja tulpadesse piisavalt tärne
	for (( j=1; j<=$tulpa; j++ ))
	do
	if [ $i -eq 1 -o $i -eq $rida ];
	then
	echo -n "*"
	elif [ $j -eq 1 -o $j -eq $tulpa ];
	then
	echo -n "*"
	else
	echo -n " "
	fi
	done
echo " "
done
